org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configuration-cache=false

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.235
loader_version_range=[1,)

mod_id=cobbleservertools
mod_name=CobbleServerTools
mod_license=MIT
mod_version=1.0.0-rc28.1
mod_group_id=net.cobbleservertools
