package net.crulim.kantonpcs.client.gui;
import java.lang.reflect.*; import java.util.*; import java.util.function.Consumer;
public final class SkinUiHooks {
 private SkinUiHooks(){} private static final Map<Object,Object> BUTTONS=Collections.synchronizedMap(new WeakHashMap<>());
 public static void install(Object screen){ try { Field f=field(screen.getClass(),"skin"); Object box=f.get(screen); invoke(box,"setVisible",new Class[]{boolean.class},false); int x=(int)invoke(box,"getX",new Class[0]); int y=(int)invoke(box,"getY",new Class[0]); int w=(int)invoke(box,"getWidth",new Class[0]); Object comp=literal("Browse skins: "+friendly((String)invoke(box,"getValue",new Class[0]))); Class<?> onPress=Class.forName("net.minecraft.client.gui.components.Button$OnPress"); Object proxy=Proxy.newProxyInstance(onPress.getClassLoader(),new Class[]{onPress},(p,m,a)->{ if(m.getName().equals("onPress")){ open(screen,box); } return null;}); Class<?> button=Class.forName("net.minecraft.client.gui.components.Button"); Object builder=button.getMethod("builder",Class.forName("net.minecraft.network.chat.Component"),onPress).invoke(null,comp,proxy); builder=builder.getClass().getMethod("bounds",int.class,int.class,int.class,int.class).invoke(builder,x,y,Math.max(80,w-28),20); Object b=builder.getClass().getMethod("build").invoke(builder); addWidget(screen,b); BUTTONS.put(screen,b); } catch(Throwable ignored){} }
 private static void open(Object screen,Object box){ try{ String cur=(String)invoke(box,"getValue",new Class[0]); Consumer<String> cb=v->{ try{invoke(box,"setValue",new Class[]{String.class},v); Object b=BUTTONS.get(screen); if(b!=null) invoke(b,"setMessage",new Class[]{Class.forName("net.minecraft.network.chat.Component")},literal("Browse skins: "+friendly(v)));}catch(Throwable ignored){}}; Class<?> sb=Class.forName("net.crulim.kantonpcs.client.gui.SkinBrowserScreen"); Object child=sb.getConstructor(Class.forName("net.minecraft.client.gui.screens.Screen"),String.class,Consumer.class).newInstance(screen,cur,cb); Field mc=fieldUp(screen.getClass(),"minecraft"); Object minecraft=mc.get(screen); invoke(minecraft,"setScreen",new Class[]{Class.forName("net.minecraft.client.gui.screens.Screen")},child); }catch(Throwable ignored){} }
 public static void renderPreview(Object screen,Object graphics){ try{ Object box=field(screen.getClass(),"skin").get(screen); String id=(String)invoke(box,"getValue",new Class[0]); if(id==null||id.isBlank())return; Object tex=Class.forName("net.minecraft.resources.ResourceLocation").getMethod("tryParse",String.class).invoke(null,id); if(tex==null)return; int x=(int)invoke(box,"getX",new Class[0])+(int)invoke(box,"getWidth",new Class[0])-24; int y=(int)invoke(box,"getY",new Class[0]); Method blit=graphics.getClass().getMethod("blit",Class.forName("net.minecraft.resources.ResourceLocation"),int.class,int.class,int.class,int.class,float.class,float.class,int.class,int.class,int.class,int.class); blit.invoke(graphics,tex,x,y,20,20,8f,8f,8,8,64,64); }catch(Throwable ignored){} }
 private static void addWidget(Object screen,Object widget)throws Exception{ Method target=null; for(Class<?> c=screen.getClass();c!=null;c=c.getSuperclass()) for(Method m:c.getDeclaredMethods()) if(m.getName().equals("addRenderableWidget")&&m.getParameterCount()==1){target=m;break;} if(target!=null){target.setAccessible(true);target.invoke(screen,widget);} }
 private static Object literal(String s)throws Exception{return Class.forName("net.minecraft.network.chat.Component").getMethod("literal",String.class).invoke(null,s);} private static Field field(Class<?> c,String n)throws Exception{Field f=c.getDeclaredField(n);f.setAccessible(true);return f;} private static Field fieldUp(Class<?> c,String n)throws Exception{for(;c!=null;c=c.getSuperclass())try{Field f=c.getDeclaredField(n);f.setAccessible(true);return f;}catch(NoSuchFieldException e){} throw new NoSuchFieldException(n);} private static Object invoke(Object o,String n,Class<?>[] p,Object...a)throws Exception{Method m=o.getClass().getMethod(n,p);m.setAccessible(true);return m.invoke(o,a);} private static String friendly(String id){if(id==null||id.isBlank())return "none";int s=id.lastIndexOf('/'),d=id.lastIndexOf('.');String v=id.substring(s+1,d>s?d:id.length()).replace('_',' ');return v;}
}
